### ISSUE TITLE
Connect with Owner account

### ISSUE THREAD

**Issue by MRE1985** [egnerfl/alfen_wallbox#23]
Hello,

Since the Alfen Wallbox is provided by my company - i do not have admin account.
When connecting with myEve app - i can connect with Owner account and see the parameters.

With the integration i get error message on the name 

  File "/config/custom_components/alfen_wallbox/config_flow.py", line 65, in async_step_user
    return await self._create_device(user_input[CONF_HOST], user_input[CONF_NAME], user_input[CONF_USERNAME], user_input[CONF_PASSWORD])
                                                            ~~~~~~~~~~^^^^^^^^^^^
KeyError: 'name'

![Alfen](https://github.com/egnerfl/alfen_wallbox/assets/135074049/ce2254a2-92ee-4796-9ff0-c3939c2ee7bd)

best regards and thank you

**Comment by egnerfl** [comment]
Please try "admin" as the user name instead of owner.

The owner account is called admin so this should be the account you use in the myEve app.

**Comment by MRE1985** [comment]
Hi, 

I tried with admin account but no luck.
With the myEve App i can login without any issue, also with the ACE Service installer. 

tried to login 
HA log:

2024-01-10 21:40:32.294 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 233, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 31, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 149, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 63, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 177, in post
    return await super().post(request, flow_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 323, in async_configure
    result = await self._async_handle_step(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 419, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/alfen_wallbox/config_flow.py", line 65, in async_step_user
    return await self._create_device(user_input[CONF_HOST], user_input[CONF_NAME], user_input[CONF_USERNAME], user_input[CONF_PASSWORD])
                                                            ~~~~~~~~~~^^^^^^^^^^^
KeyError: 'name'


Alfen log: 
No log


When connected with myEve and connect ha - session with myEve is failed (TLS handshake failed)

Hope you have some ideas?

**Comment by LiveDrunk** [comment]
Not sure this will be of assistance but i managed to get the wallbox in Home Assistant by closing the other connections...
- Make sure that the ACE Service Installer Application is not opened on your device.

https://knowledge.alfen.com/space/IN/697827329/What+should+I+do+when+I+get+a+connection+error+with+my+charging+station+in+the+MyEve+app%3F

It might not like multiple connections, hope it helps else it might be worth mentioning in the readme ?

**Comment by MRE1985** [comment]
S

**Comment by MRE1985** [comment]
When leaving the comment empty - it's not added
