### ISSUE TITLE
Integration not working in HA after update

### ISSUE THREAD

**Issue by Peet3kabo** [egnerfl/alfen_wallbox#32]
Yesterday I did an update to the latest version of this add on.
After that I have no working integration anymore.
Tried restart of HA, restart the wallbox.
I can reach it thru the myeve app, no idea what else to do.
Have an error in the log of HA:
Deze fout is ontstaan door een aangepaste integratie.

Logger: homeassistant
Bron: custom_components/alfen_wallbox/config_flow.py:77
integratie: Alfen Wallbox (documentatie)
Eerst voorgekomen: 09:57:39 (1 gebeurtenissen)
Laatst gelogd: 09:57:39

Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/discovery_flow.py", line 108, in _async_start
    await gather_with_limited_concurrency(FLOW_INIT_LIMIT, *init_coros)
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 106, in gather_with_limited_concurrency
    return await gather(
           ^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 104, in sem_task
    return await task
           ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1267, in async_init
    flow, result = await self._async_init(flow_id, handler, context, data)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1297, in _async_init
    result = await self._async_handle_step(flow, flow.init_step, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 518, in _async_handle_step
    result: _FlowResultT = await getattr(flow, method)(user_input)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/alfen_wallbox/config_flow.py", line 77, in async_step_zeroconf
    return await self._create_entry(user_input[KEY_IP], None, user_input[CONF_USERNAME], user_input[CONF_PASSWORD])
                                    ~~~~~~~~~~^^^^^^^^
TypeError: 'ZeroconfServiceInfo' object is not subscriptable

**Comment by Peet3kabo** [comment]
Edit, if I try to reload the integration it gives the message to restart HA to finish the installation. Looks like it's stuck in a installation somewhere. Did restart HA several times but that didn't resolve the problem.

Edit 2, I did several updates on hacs in one go before restarting HA. Also it was before I updated to the latest HA version. So restored backup to a previous working HA, the day before........then updated HA to latest version, next step was update alfen integration and restart HA. Same problem occurred with same error message
