### ISSUE TITLE
Unexpected error creating device.

### ISSUE THREAD

**Issue by scallidotcom** [egnerfl/alfen_wallbox#4]
I am unable to create the device in Homeassistant

Logger: custom_components.alfen_wallbox.config_flow
Source: custom_components/alfen_wallbox/alfen.py:180
Integration: Alfen Wallbox (documentation)
First occurred: 02:45:12 (6 occurrences)
Last logged: 02:52:52

Unexpected error creating device
Traceback (most recent call last):
  File "/config/custom_components/alfen_wallbox/config_flow.py", line 42, in _create_device
    await device.init()
  File "/config/custom_components/alfen_wallbox/alfen.py", line 37, in init
    await self.async_get_info()
  File "/config/custom_components/alfen_wallbox/alfen.py", line 95, in async_get_info
    self.info = AlfenDeviceInfo(response_json)
  File "/config/custom_components/alfen_wallbox/alfen.py", line 180, in __init__
    if ALFEN_PRODUCT_MAP[self.model_id] is None:
KeyError: 'NG910-60587'

**Comment by gizmoy2k** [comment]
In const.py copy or replace one of the products with your model NG910-60587

It cannot create because it is not in this list

**Comment by scallidotcom** [comment]
thank you it working now.
