### ISSUE TITLE
Error adding (second) charger 

### ISSUE THREAD

**Issue by sweebee** [egnerfl/alfen_wallbox#8]
I have 2 alfen charge points, 1 Eve Single Pro Which i've added without any problems.

I tried to add the second one Eve Single S-line and i got the following error:

```
Unexpected error creating device
Traceback (most recent call last):
  File "/config/custom_components/alfen_wallbox/config_flow.py", line 42, in _create_device
    await device.init()
  File "/config/custom_components/alfen_wallbox/alfen.py", line 37, in init
    await self.async_get_info()
  File "/config/custom_components/alfen_wallbox/alfen.py", line 95, in async_get_info
    self.info = AlfenDeviceInfo(response_json)
  File "/config/custom_components/alfen_wallbox/alfen.py", line 180, in __init__
    if ALFEN_PRODUCT_MAP[self.model_id] is None:
KeyError: 'NG910-60587'
```

**Comment by maedball** [comment]
Ok that answers my question in the discussions ;-). It seems like this is an issue.
